### ISSUE TITLE
老哥没有使用文档吗

### ISSUE THREAD

**Issue by woniuxia** [Zuoqiu-Yingyi/siyuan-publish#1]
RT

**Comment by Zuoqiu-Yingyi** [comment]
目前是只实现了基础功能, 想写文档都没有东西写, 等功能完善一下就着手写:heart:

**Comment by Zuoqiu-Yingyi** [comment]
[README-zh\_SC.md](https://github.com/Zuoqiu-Yingyi/siyuan-publish/blob/main/docs/README-zh_SC.md)
