### ISSUE TITLE
是不是头部样式好像有点问题呢？

### ISSUE THREAD

**Issue by winter60** [Zuoqiu-Yingyi/siyuan-publish#2]
![image](https://user-images.githubusercontent.com/23653326/185399599-80beaf7e-4eaf-42db-a9d5-442c442e08bb.png)
用的明亮模式，没有改动

**Comment by Zuoqiu-Yingyi** [comment]
需要设置 `Render.File.Style.Base` 字段, 该字段为思源基础样式文件的 URL, 建议设置为思源安装目录 `/resource/stage/build/mobile/` 下的 CSS 文件访问 URL, 例如该 CSS 文件名为 `base.2ad8890755ebaf8cc6d3.css`, 那么该选项设置为 `/stage/build/mobile/base.2ad8890755ebaf8cc6d3.css`

因为思源每个版本样式文件文件名都不一致, 因此需要手动设置
